# -*- coding: utf-8 -*-
"""cifar 10 using image classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yyoVzWFDrzAqBVqsW-uOlM5EyNBAFrm
"""

!pip install tensorflow

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

ci = keras.datasets.cifar10
(x_train,y_train),(x_test,y_test)=ci.load_data()

x_train,x_test = x_train/255.0,x_test/255.0

import matplotlib.pyplot as plt
plt.imshow(x_train[7])

y_train[7]

model = keras.Sequential([
    layers.Flatten(input_shape=(32,32,3)),
    layers.Dense(520, activation='relu'),
    layers.Dense(10, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train,y_train, epochs= 5)

pred = model.predict(x_test)

import numpy as np
y_pred1 = np.argmax(pred, axis=1)

y_pred1[7]

y_test[7]

plt.imshow(x_test[7])